### ISSUE TITLE
Fix markdown to support collapsible-sections in Github pages

### ISSUE THREAD

**Issue by mccright** [mccright/rrl#7]
Fix markdown to support normal Github markdown inside collapsible-sections in Github pages

**Comment by mccright** [comment]
There is a lot of unclear and sometimes conflicting guidance for doing so for pages that employed collapsible sections and Github markdown.  For this site, the most important *fixes* were:  
  * Always put an empty line after collapsible section tags.  
  * Put double quotes around any string that included whitespace in the site config file (_config.yml).  
  * Use the `markdown: GFM` processor in the site config file (_config.yml).  

My _config.yml file:  
```yml
title: "Recreational Reading Log"
description: "List of my reading since 2022 July 25"
logo: https://mccright.github.io/rrl/m.svg
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll 
markdown: GFM
```
